@startuml
== deleteCacheFirstPattern ==
App --> Service: update
Service --> Cache: deleteCache
note left: updateCache?
Service -> Redis: setNX+expire
Redis --> Redis: lock
Service --> DB: updateDB
App --> Service: select
Service --> Cache: select
Cache --> Cache: nothing
Service --> DB: select
Service --> Cache: addCache

@enduml