/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class richard_test_jni_TestJNI */

#ifndef _Included_richard_test_jni_TestJNI
#define _Included_richard_test_jni_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     richard_test_jni_TestJNI
 * Method:    go
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_richard_test_jni_TestJNI_go
  (JNIEnv *, jobject);

/*
 * Class:     richard_test_jni_TestJNI
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_richard_test_jni_TestJNI_run
  (JNIEnv *, jobject);

/*
 * Class:     richard_test_jni_TestJNI
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_richard_test_jni_TestJNI_getName
  (JNIEnv *, jobject);

/*
 * Class:     richard_test_jni_TestJNI
 * Method:    sort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_richard_test_jni_TestJNI_sort
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
