type("t", Key.CTRL+ Key.ALT)
wait(1)
type("some text" + Key.TAB + "more text" + Key.TAB + Key.ENTER)
wait(1)
type("libreoffice --calc &" + Key.ENTER)
wait(2)
type("this is  a test" + Key.ENTER)
#mouseMove(Location(82, 230))
rightClick(Location(82, 230))
wait(2)
a=find("1659338200587.png")
click(a)
print(Env.getClipboard())
